### ISSUE TITLE
Php docker Doesn't work on Apple M1

### ISSUE THREAD

**Issue by amine2233** [Sylius/docker-images#5]
I have an issue using my computer which is Apple M1, 

I use Docker Desktop and i would'n use Rosetta to run my docker, so when would run the sylius docker-composer i have an issue

`no matching manifest for linux/arm64/v8 in the manifest list entries` 

can you help me to resolve this issue or maybe need just to update the php image,

Thanks for your awesome work

**Comment by Ferror** [comment]
@amine2233 define `--platform linux/amd64` when executing docker or `platform: linux/amd64` when using docker-compose
